<SpeedLabel>:
    color: (0, 0, 0, 1)
    size_hint: (0.2, 0.2)
    pos_hint: {"center_x": 0.5, "center_y": 0.8}
    font_size: self.width / 4

<Arrow>:
    size_hint: (0.4, None)
    height: self.width
    color: (0, 0, 0, 1)

<LeftArrow>:
    source: "images/fleche-gauche.png"
    pos_hint: {"center_x": 0.25, "center_y": 0.5}

<RightArrow>:
    source: "images/fleche-droite.png"
    pos_hint: {"center_x": 0.75, "center_y": 0.5}
